# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# create Fibonacci metho to list fibonacci number
# add fibo numbers to an array
# find the sum of all even fibo numbers less than 4mil

	def fibo(n)
		return n if n < 2
	  fib = [1,2]
		n.times do
			fib << fib[-1] + fib[-2]
		end	
		return fib.last
	end

	# puts fibo(31)

	max = 4_000_000_000
	i = 1
  sum = 0

	while((x = fibo(i)) < max)
	  sum += x if x % 2 == 0
	  i += 1
	end

	puts sum





